# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1df9afd7ca53ed5fc8aba681b0fc9721eb176d3d9f2b992835e0d60bea695a11e9fe226d5af023e8f3d2db69db25771446c80642a54c53e8db7799e0e4a13666

test:
  secret_key_base: aacc16b0516e5c77658f2777fec08ec8a48d682669a06101b44db674258bc2d73d162fff50ce5dd8c8c16225d30d2442d7b56f49ae1042be95785793bbf7ea98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
