# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3a46978aaeaa68266d23bbfc2965100bc0c685db0f8f4672aff82cc6ea29b4ee2224e4917aa250f2e178e3fce50d7d4bcb1f07ade383da9ace967526e87f9d7

test:
  secret_key_base: b016d54ed18b6fb20e217e05504e1421d428305aa8f69a45a66a0071cfa512514b9a7d588ea5e5fa8322f8de271055a229450afac3c8a4847212fa9cff3de862

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
